#!/usr/bin/env bash
# Branch, copy user skills into the project, commit, push, and open a PR.
#
# Usage:
#   publish-skills.sh [target] [--on-existing=skip|overwrite] [--branch=<name>]
#
# Preview what's new vs. already in the project first with: sync-skills.sh check
# Source dir override: USER_SKILLS_DIR=/path publish-skills.sh ...
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ON_EXISTING="skip"
TARGET=""
BRANCH=""
for arg in "$@"; do
  case "$arg" in
    # --on-conflict is accepted as a deprecated alias for --on-existing.
    --on-existing=*|--on-conflict=*) ON_EXISTING="${arg#*=}" ;;
    --branch=*)      BRANCH="${arg#*=}" ;;
    -*) echo "error: unknown flag '$arg'" >&2; exit 2 ;;
    *)  TARGET="$arg" ;;
  esac
done
if [[ "$ON_EXISTING" != "skip" && "$ON_EXISTING" != "overwrite" ]]; then
  echo "error: --on-existing must be 'skip' or 'overwrite' (got '$ON_EXISTING')" >&2
  exit 2
fi

# --- preflight -------------------------------------------------------------
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
  echo "error: not inside a git repository" >&2; exit 1; }
command -v gh >/dev/null 2>&1 || {
  echo "error: GitHub CLI 'gh' not found — install it and run 'gh auth login'" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || {
  echo "error: 'gh' is not authenticated — run 'gh auth login'" >&2; exit 1; }
git remote get-url origin >/dev/null 2>&1 || {
  echo "error: no 'origin' remote to push to" >&2; exit 1; }

ROOT="$(git rev-parse --show-toplevel)"
TARGET="${TARGET:-$ROOT/.claude/skills}"
SETTINGS="$(dirname "$TARGET")/settings.json"
START_BRANCH="$(git branch --show-current)"

BASE="$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name 2>/dev/null || true)"
[[ -z "$BASE" ]] && BASE="main"

if [[ -z "$BRANCH" ]]; then
  BRANCH="chore/copy-user-skills-$(date +%Y%m%d-%H%M%S)"
fi

echo "Base branch:    $BASE"
echo "New branch:     $BRANCH"
echo "Target:         $TARGET"
echo "On existing:    $ON_EXISTING"
echo

# --- branch + copy ---------------------------------------------------------
git switch -c "$BRANCH"

bash "$SCRIPT_DIR/sync-skills.sh" apply "$TARGET" --on-existing="$ON_EXISTING"

git add -- "$TARGET" "$SETTINGS"

if git diff --cached --quiet; then
  echo
  echo "No changes to commit (nothing new to copy, settings already set). Rolling back branch."
  git switch "${START_BRANCH:-$BASE}"
  git branch -D "$BRANCH"
  exit 0
fi

# --- commit + push + PR ----------------------------------------------------
git commit -F - <<'MSG'
chore: vendor user-level skills into the project

Copy the developer's ~/.claude/skills into .claude/skills so they are
available in Claude cloud/web code, which cannot read local user skills.

Also pre-approve the Linear MCP (mcp__Linear, mcp__claude_ai_Linear) in
.claude/settings.json so Claude cloud doesn't prompt for permission on every
Linear issue update.

Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>
MSG

git push -u origin "$BRANCH"

PR_URL="$(gh pr create --base "$BASE" --head "$BRANCH" \
  --title "chore: vendor user-level skills into the project" \
  --body "$(cat <<'BODY'
Copies the developer's user-level skills (`~/.claude/skills`) into `.claude/skills`
so they are available in Claude cloud/web code, which cannot read local user skills.

Also pre-approves the Linear MCP in `.claude/settings.json`:

```json
{
  "permissions": {
    "allow": ["mcp__Linear", "mcp__claude_ai_Linear"]
  }
}
```

so Claude cloud doesn't prompt for permission every time it reads or updates
Linear issues.

Generated by the `copy-user-skills` skill. Review the vendored skills and merge.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
BODY
)")"

echo
echo "PR opened: $PR_URL"
